// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SahinSoft.Web.Data;

#nullable disable

namespace SahinSoft.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260727182243_AddRemainingWebsiteProducts")]
    partial class AddRemainingWebsiteProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SahinSoft.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinimumStockQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("StockQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("TaxRateId")
                        .HasColumnType("int");

                    b.Property<bool>("TrackStock")
                        .HasColumnType("bit");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("WebsitePath")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasFilter("[Barcode] IS NOT NULL");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StockCode")
                        .IsUnique();

                    b.HasIndex("TaxRateId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Ingenico",
                            CategoryId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "IDE280",
                            Name = "Ingenico IDE280",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YK-0001",
                            StockQuantity = 0m,
                            TaxRateId = 1,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "yazarkasa-pos.html"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Ingenico",
                            CategoryId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "Move 5000F",
                            Name = "Ingenico Move 5000F",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YK-0002",
                            StockQuantity = 0m,
                            TaxRateId = 1,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "yazarkasa-pos.html"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "PayGo",
                            CategoryId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "SP630PRO ECR",
                            Name = "PAYGO SP630PRO ECR",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YK-0003",
                            StockQuantity = 0m,
                            TaxRateId = 1,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "yazarkasa-pos.html"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Profilo",
                            CategoryId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "S900",
                            Name = "Profilo S900",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YK-0004",
                            StockQuantity = 0m,
                            TaxRateId = 1,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "yazarkasa-pos.html"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "inPOS",
                            CategoryId = 1,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "m530",
                            Name = "inPOS m530 Mobil POS",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YK-0005",
                            StockQuantity = 0m,
                            TaxRateId = 1,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "yazarkasa-pos.html"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "CAS",
                            CategoryId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "CL3000",
                            Name = "CAS CL3000 Market Terazisi",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "TR-0001",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "teraziler.html"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "CAS",
                            CategoryId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "CL8000",
                            Name = "CAS CL8000 Dokunmatik Terazi",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "TR-0002",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "teraziler.html"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "CAS",
                            CategoryId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "CN-1",
                            Name = "CAS CN-1 Sistem Terazisi",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "TR-0003",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "teraziler.html"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Digi",
                            CategoryId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "SM100P",
                            Name = "Digi SM100P Boyunlu Terazi",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "TR-0004",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "teraziler.html"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Digi",
                            CategoryId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "SM-120T",
                            Name = "Digi SM-120T Dokunmatik Terazi",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "TR-0005",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "teraziler.html"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "CAS",
                            CategoryId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "ER-JR",
                            Name = "CAS ER-JR Masaüstü Terazi",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "TR-0006",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "teraziler.html"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "CAS",
                            CategoryId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "FW-500",
                            Name = "CAS FW-500 Su Geçirmez Terazi",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "TR-0007",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "teraziler.html"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "CAS",
                            CategoryId = 2,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "PDI",
                            Name = "CAS PDI Ankastre Kasa Terazisi",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "TR-0008",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "teraziler.html"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Hillpos",
                            CategoryId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "HRS-28",
                            Name = "Hillpos HRS-28",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "BO-0001",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "barkod-okuyucular.html"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Hillpos",
                            CategoryId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "HSC-82",
                            Name = "Hillpos HSC-82",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "BO-0002",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "barkod-okuyucular.html"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Hillpos",
                            CategoryId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "HSD-92",
                            Name = "Hillpos HSD-92",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "BO-0003",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "barkod-okuyucular.html"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Newland",
                            CategoryId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "TP-13",
                            Name = "Newland TP-13",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "BO-0004",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "barkod-okuyucular.html"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Newland",
                            CategoryId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "TP-14",
                            Name = "Newland TP-14",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "BO-0005",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "barkod-okuyucular.html"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Hillpos",
                            CategoryId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "HS-6700",
                            Name = "Hillpos HS-6700",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "BO-0006",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "barkod-okuyucular.html"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Hillpos",
                            CategoryId = 3,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "VS-6800",
                            Name = "Hillpos VS-6800",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "BO-0007",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "barkod-okuyucular.html"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Argox",
                            CategoryId = 4,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "OS-214 Plus",
                            Name = "Argox OS-214 Plus Barkod Yazıcı",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YZ-0001",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "yazicilar.html"
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Hillpos",
                            CategoryId = 4,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "HDT-400",
                            Name = "Hillpos HDT-400 Barkod Yazıcı",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YZ-0002",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "yazicilar.html"
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Hillpos",
                            CategoryId = 4,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "HTT-440",
                            Name = "Hillpos HTT-440 Barkod Yazıcı",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YZ-0003",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "yazicilar.html"
                        },
                        new
                        {
                            Id = 24,
                            Brand = "TSC",
                            CategoryId = 4,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "TTP-244CE",
                            Name = "TSC TTP-244CE Barkod Yazıcı",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YZ-0004",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "yazicilar.html"
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Xprinter",
                            CategoryId = 4,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "XP-470B",
                            Name = "Xprinter XP-470B Barkod Yazıcı",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YZ-0005",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "yazicilar.html"
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Hillpos",
                            CategoryId = 4,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "H380",
                            Name = "Hillpos H380 Fiş Yazıcı",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YZ-0006",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "yazicilar.html"
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Hillpos",
                            CategoryId = 4,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "Q800",
                            Name = "Hillpos Q800 Fiş Yazıcı",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YZ-0007",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "yazicilar.html"
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Bixolon",
                            CategoryId = 4,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "SPP-R310",
                            Name = "Bixolon SPP-R310 Mobil Fiş Yazıcı",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YZ-0008",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "yazicilar.html"
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Chainway",
                            CategoryId = 5,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "C61",
                            Name = "Chainway C61",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "ET-0001",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "el-terminali.html"
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Chainway",
                            CategoryId = 5,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "C66",
                            Name = "Chainway C66",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "ET-0002",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "el-terminali.html"
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Hillpos",
                            CategoryId = 5,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "C7X",
                            Name = "Hillpos C7X Tablet",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "ET-0003",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "el-terminali.html"
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Hillpos",
                            CategoryId = 5,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "CM550X",
                            Name = "Hillpos CM550X",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "ET-0004",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "el-terminali.html"
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Hillpos",
                            CategoryId = 5,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "HT42",
                            Name = "Hillpos HT42",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "ET-0005",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "el-terminali.html"
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Hillpos",
                            CategoryId = 5,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "HT42K",
                            Name = "Hillpos HT42K",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "ET-0006",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "el-terminali.html"
                        },
                        new
                        {
                            Id = 35,
                            Brand = "Hillpos",
                            CategoryId = 5,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "HT44",
                            Name = "Hillpos HT44",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "ET-0007",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "el-terminali.html"
                        },
                        new
                        {
                            Id = 36,
                            Brand = "Hillpos",
                            CategoryId = 6,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "Touch Pro 15",
                            Name = "Hillpos Touch Pro 15",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "PC-0001",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "dokunmatik-pos.html"
                        },
                        new
                        {
                            Id = 37,
                            Brand = "Hillpos",
                            CategoryId = 6,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "All-in-One Dual POS",
                            Name = "Hillpos All-in-One Dual POS",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "PC-0002",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "dokunmatik-pos.html"
                        },
                        new
                        {
                            Id = 38,
                            Brand = "Hillpos",
                            CategoryId = 6,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "Slim Touch 15",
                            Name = "Hillpos Slim Touch 15",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "PC-0003",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "dokunmatik-pos.html"
                        },
                        new
                        {
                            Id = 39,
                            Brand = "Hillpos",
                            CategoryId = 6,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "Kiosk POS 21.5",
                            Name = "Hillpos Kiosk POS 21.5",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "PC-0004",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "dokunmatik-pos.html"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 7,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Name = "Özel ERP & CRM Yazılımları",
                            ProductType = "Yazılım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YW-0001",
                            StockQuantity = 0m,
                            TaxRateId = 3,
                            TrackStock = false,
                            Unit = "Adet",
                            WebsitePath = "kurumsal-yazilim.html"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 7,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Name = "Stok ve Depo Yönetimi Yazılımı",
                            ProductType = "Yazılım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YW-0002",
                            StockQuantity = 0m,
                            TaxRateId = 3,
                            TrackStock = false,
                            Unit = "Adet",
                            WebsitePath = "kurumsal-yazilim.html"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 7,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Name = "Fabrika ve Üretim Takibi Yazılımı",
                            ProductType = "Yazılım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YW-0003",
                            StockQuantity = 0m,
                            TaxRateId = 3,
                            TrackStock = false,
                            Unit = "Adet",
                            WebsitePath = "kurumsal-yazilim.html"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 7,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Name = "API ve Donanım Entegrasyonları",
                            ProductType = "Yazılım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YW-0004",
                            StockQuantity = 0m,
                            TaxRateId = 3,
                            TrackStock = false,
                            Unit = "Adet",
                            WebsitePath = "kurumsal-yazilim.html"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 7,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Name = "GİB & E-Fatura Çözümleri",
                            ProductType = "Yazılım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "YW-0005",
                            StockQuantity = 0m,
                            TaxRateId = 3,
                            TrackStock = false,
                            Unit = "Adet",
                            WebsitePath = "kurumsal-yazilim.html"
                        },
                        new
                        {
                            Id = 45,
                            Brand = "Genel",
                            CategoryId = 8,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "Metal Kasa",
                            Name = "Para Çekmecesi",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "PE-0001",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "index.html"
                        },
                        new
                        {
                            Id = 46,
                            Brand = "Genel",
                            CategoryId = 8,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "Fiyat Sorgulama Terminali",
                            Name = "Fiyat Gör Cihazı",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "PE-0002",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "index.html"
                        },
                        new
                        {
                            Id = 47,
                            Brand = "Genel",
                            CategoryId = 8,
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinimumStockQuantity = 0m,
                            Model = "Mobil Fiş Yazıcı",
                            Name = "Mobil Yazıcı",
                            ProductType = "Donanım",
                            PurchasePrice = 0m,
                            SalePrice = 0m,
                            StockCode = "PE-0003",
                            StockQuantity = 0m,
                            TaxRateId = 2,
                            TrackStock = true,
                            Unit = "Adet",
                            WebsitePath = "index.html"
                        });
                });

            modelBuilder.Entity("SahinSoft.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("WebsitePath")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "YAZARKASA",
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Yazar Kasa POS",
                            WebsitePath = "yazarkasa-pos.html"
                        },
                        new
                        {
                            Id = 2,
                            Code = "TERAZI",
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Teraziler",
                            WebsitePath = "teraziler.html"
                        },
                        new
                        {
                            Id = 3,
                            Code = "BARKOD",
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Barkod Okuyucular",
                            WebsitePath = "barkod-okuyucular.html"
                        },
                        new
                        {
                            Id = 4,
                            Code = "YAZICI",
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Yazıcılar",
                            WebsitePath = "yazicilar.html"
                        },
                        new
                        {
                            Id = 5,
                            Code = "ELTERM",
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "El Terminalleri",
                            WebsitePath = "el-terminali.html"
                        },
                        new
                        {
                            Id = 6,
                            Code = "POSPC",
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Dokunmatik POS",
                            WebsitePath = "dokunmatik-pos.html"
                        },
                        new
                        {
                            Id = 7,
                            Code = "YAZILIM",
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Yazılım ve Entegrasyon",
                            WebsitePath = "kurumsal-yazilim.html"
                        },
                        new
                        {
                            Id = 8,
                            Code = "POSEKIP",
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "POS Çevre Birimleri",
                            WebsitePath = "index.html"
                        });
                });

            modelBuilder.Entity("SahinSoft.Domain.Entities.TaxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExempt")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TaxRates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "KDV10",
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsExempt = false,
                            Name = "KDV %10",
                            Rate = 10m
                        },
                        new
                        {
                            Id = 2,
                            Code = "KDV20",
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsExempt = false,
                            Name = "KDV %20",
                            Rate = 20m
                        },
                        new
                        {
                            Id = 3,
                            Code = "MUAF",
                            CreatedAtUtc = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsExempt = true,
                            Name = "KDV Muafiyet",
                            Rate = 0m
                        });
                });

            modelBuilder.Entity("SahinSoft.Web.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SahinSoft.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SahinSoft.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SahinSoft.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SahinSoft.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SahinSoft.Domain.Entities.Product", b =>
                {
                    b.HasOne("SahinSoft.Domain.Entities.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SahinSoft.Domain.Entities.TaxRate", "TaxRate")
                        .WithMany()
                        .HasForeignKey("TaxRateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("TaxRate");
                });

            modelBuilder.Entity("SahinSoft.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
